// import header from "./_components/header"
import footer from "./_components/footer";

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body>
//         <header />
//         {children}
//         </body>
//     </html>
//   )
// }

import Header from "./_components/header";
import Footer from "./_components/footer";
import Test from "./_components/test";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {/* <Test /> */}
        {children}
        <Footer />
      </body>
    </html>
  );
}
